export const RESEARCH_AUTH_SUCCESS = "RESEARCH_AUTH_SUCCESS";
export const RESEARCH_AUTH_FAIL = "RESEARCH_AUTH_FAIL";
export const RESEARCH_REGISTER_SUCCESS = "RESEARCH_REGISTER_SUCCESS";
export const RESEARCH_REGISTER_FAIL = "RESEARCH_REGISTER_FAIL";

export const RESEARCH_LOADING = "RESEARCH_LOADING";
export const RESEARCH_LOADED = "RESEARCH_LOADED";

export const RESEARCH_GET_LIST_USER = "RESEARCH_GET_LIST_USER";
export const RESEARCH_GET_LIST_ALL = "RESEARCH_GET_LIST_ALL";
