// AUTH AND REGISTER
export const RESEARCH_AUTH_SUCCESS = "RESEARCH_AUTH_SUCCESS";
export const RESEARCH_AUTH_FAIL = "RESEARCH_AUTH_FAIL";
export const RESEARCH_REGISTER_SUCCESS = "RESEARCH_REGISTER_SUCCESS";
export const RESEARCH_REGISTER_FAIL = "RESEARCH_REGISTER_FAIL";

// LOAD DATA
export const RESEARCH_LOADING = "RESEARCH_LOADING";
export const RESEARCH_LOADED = "RESEARCH_LOADED";

// RESEARCH USER
export const RESEARCH_GET_LIST_USER = "RESEARCH_GET_LIST_USER";
export const RESEARCH_GET_LIST_ALL = "RESEARCH_GET_LIST_ALL";

// UPLOAD FILE
export const RESEARCH_GET_UPLOAD_FILE = "RESEARCH_GET_UPLOAD_FILE";

//  TAGS
export const COLLECT_TAG = "COLLECT_TAG";
export const CLEAR_TAG = "CLEAR_TAG";

// RESEARCH LIST
export const RESEARCH_ADD_LIST_SUCCESS = "RESEARCH_ADD_LIST_SUCCESS";

// GET ERROR
export const RESEARCH_ERROR = "RESEARCH_ERROR";
